#! /bin/sh
#
# gen_dev dev4 vars.src vars
#
# Generate an overlay config for devNNN from vars.src and write to vars
#

NAME=$1
TEMPLATE=$2
VARFILE=$3

## Allocate 10 ports per node
##   .7 - http

NUMBER=${NAME##dev}
BASE=$((10000 + 10 * $NUMBER))
HANDOFFPORT=$(($BASE + 9))
ALUMWEBPORT=$(($BASE + 8))
ALUMAPIPORT=$(($BASE + 7))
WEBPORT=$(($BASE + 6))
NODENAME="alum$NUMBER@127.0.0.1"

echo "Generating $NAME - node='$NODENAME' http=$WEBPORT handoff=$HANDOFFPORT"
sed -e "s/@NODE@/$NODENAME/" \
    -e "s/@WEBPORT@/$WEBPORT/" \
    -e "s/@ALUMWEBPORT@/$ALUMWEBPORT/" \
    -e "s/@ALUMAPIPORT@/$ALUMAPIPORT/" \
    -e "s/@HANDOFFPORT@/$HANDOFFPORT/" < $TEMPLATE > $VARFILE
